services:
  db-test:
    image: postgres:14-alpine
    container_name: db-test
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    ports:
      - "5433:5432"
    volumes:
      - ems-db-test-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq-test:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/ # Persistent storage for RabbitMQ data
      - rabbitmq_log:/var/log/rabbitmq/  # Persistent storage for RabbitMQ
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s

volumes:
  ems-db-test-data:
  rabbitmq_data:
  rabbitmq_log: