services:
  db-test:
    image: postgres:14-alpine
    container_name: db-test
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    ports:
      - "5433:5432"
    volumes:
      - ems-db-test-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ems-db-test-data: